#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
# Requirements:
# In between each iteration of the loop, add a sleep 2
# I am invincible!!! when receiving a SIGTERM signal
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo I am invincible!!!" SIGTERM
done
